### ISSUE TITLE
请问Mixup代码可以开源一下吗？

### ISSUE THREAD

**Issue by NeedC** [milleniums/underwater-object-detection-mmdetection#1]

**Comment by milleniums** [comment]
你好，我们在A榜使用Mixup取得了很好的效果，但是在B榜由于出现分数下滑就没有再使用。你可以参考[比赛团队：想测水深](https://github.com/Wakinguup/Underwater_detection/blob/master/code/mmdet/datasets/pipelines/transforms.py)的开源项目里的实现
