### ISSUE TITLE
请问你们的mixup，在loss计算时，是直接进行计算，还是给于lamda,1-lamda的权重进行计算？

### ISSUE THREAD

**Issue by Dragonsson** [milleniums/underwater-object-detection-mmdetection#2]

**Comment by milleniums** [comment]
你好，lambd取0.5，直接进行计算。代码实现参考[我的队友的github](https://github.com/sankin97/Underwater_detection/blob/master/mmdet/datasets/pipelines/transforms.py)

**Comment by Dragonsson** [comment]
这样会导致loss扩大两倍，有没有不良影响？当lamda取0.5时，loss1+loss2 是lamda*loss1+(1-lamda)*loss2的两倍

**Comment by milleniums** [comment]
你说的是图片分类中的Mixup吧？

**Comment by Dragonsson** [comment]
对的，分类跟检测的loss计算方法是不是不一样？

**Comment by milleniums** [comment]
肯定不一样。分类和检测的Mixup不一样的。 [请参考这里](https://www.zhihu.com/question/308572298)

**Comment by Dragonsson** [comment]
好的，多谢
